### PR TITLE
Issue #49 Update docker version to 1.12.6

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by brgnepal** [comment]
@praveenkumar as per docker `1.12.6` commit, path has now changed from `/make_iso.sh` to `/tmp/make_iso.sh`. See here https://github.com/boot2docker/boot2docker/commit/f3e4485ff8fb2f5aa81d1f7834a82fa5ec33aeaf.

**Comment by gbraad** [comment]
will this update to a new boot2docker with a more recent kernel version? because the current version has a possible issue with Ryzen CPUs: https://github.com/minishift/minishift/issues/1022

**Comment by hferentschik** [comment]
@praveenkumar @budhrg I think this relates to issues #26

**Comment by hferentschik** [comment]
I am also wondering why we not should update to the latest available version issue #28. Obviously there are cases to be made for either. This pull requests aligns Docker versions between our ISOs. Upgrading to the latest gives user some more features.

**Comment by praveenkumar** [comment]
> I am also wondering why we not should update to the latest available version issue #28. 

Right, I think this will resolve #28 also but as I mentioned on the issue, we should have consistent docker version across all our ISO and right now it's 1.12.6

**Comment by brgnepal** [comment]
> I mentioned on the issue, we should have consistent docker version across all our ISO and right now it's 1.12.6

That's means why not go for 1.13.1 which is the last version before they moved to community edition (CE) kind of version (See [here](https://github.com/boot2docker/boot2docker/tags?after=v17.04.0-ce-rc1)). Let sync this version is CentOS ISO too.

**Comment by hferentschik** [comment]
@praveenkumar can we not upgrade the CentOS ISO version as well? Or is there nothing later?

**Comment by praveenkumar** [comment]
> Let sync this version is centos ISO too.

@budhrg , @hferentschik  No, docker version which part of centos is comes from offical repo and we don't have ownership there and we should not use unofficial repo for CentOS just for docker version upgrade because same version what stick to our RHEL ISO also.

**Comment by brgnepal** [comment]
@praveenkumar Please update commit message with docker version for easy track.

**Comment by praveenkumar** [comment]
@gbraad let CI run for this and then we can merge this PR.

**Comment by brgnepal** [comment]
@praveenkumar CI is fine. Now, it can be merged.

**Review by gbraad — APPROVED** [review]

**Review by brgnepal — APPROVED** [review]

**Pull request merged**
