### PR TITLE
Fix #29 Add cifs-utils to allow mounting fileshares

### LINKED ISSUE #29: Add `cifs-utils` to allow mounting cifs fileshares
To allow mounting of fileshares, as described in minishift/minishift#316, we need to add `cifs-utils` to the image.

### PR DESCRIPTION
**Pull request by gbraad**
Added `cifs-utils` and dependencies into `/rootfs/`. This allows mounting of fileshares using the smb protocol.

### CODE REVIEW

**Comment by gbraad** [comment]
```
$ make
```

```
ISO_URL=file:///var/workspaces/minishift-b2d-iso/build/minishift-b2d.iso; /var/workspaces/minishift/bin/minishift start --openshift-version=v1.4.1 --iso-url=$ISO_URL
$ minishift ssh
```

```
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec
docker@minishift:~$ mkdir /tmp/disks
docker@minishift:~$ sudo mount -t cifs //10.0.21.33/Disks /tmp/disks/
Password for root@//10.0.21.33/Disks:
docker@minishift:~$ ls /tmp/disk/
mnt_map  sda1/
docker@minishift:~$
```

**Comment by brgnepal** [comment]
retest this please

**Comment by brgnepal** [comment]
retest this please

**Comment by brgnepal** [comment]
retest this please

**Comment by brgnepal** [comment]
retest this please

**Comment by brgnepal** [comment]
Tests are passing for me locally http://pastebin.test.redhat.com/456628

**Comment by brgnepal** [comment]
retest this please

**Comment by gbraad** [comment]
retest this please

**Comment by gbraad** [comment]
```
[gbraad@baobao minishift-b2d-iso]$ avocado run tests/test.py
JOB ID     : 1c47a7499551828692622972916718145653a34e
JOB LOG    : /home/gbraad/avocado/job-results/job-2017-02-17T23.26-1c47a74/job.log
TESTS      : 7
 (1/7) tests/test.py:MinishiftISOTest.test_boot_vm_out_of_iso: PASS (436.15 s)
 (2/7) tests/test.py:MinishiftISOTest.test_ssh_connection_to_vm: PASS (0.14 s)
 (3/7) tests/test.py:MinishiftISOTest.test_ip_of_vm: PASS (0.04 s)
 (4/7) tests/test.py:MinishiftISOTest.test_docker_env_evaluable: PASS (0.04 s)
 (5/7) tests/test.py:MinishiftISOTest.test_cifs_mount: PASS (0.14 s)
 (6/7) tests/test.py:MinishiftISOTest.test_stopping_vm: PASS (1.43 s)
 (7/7) tests/test.py:MinishiftISOTest.test_delete_vm: PASS (0.23 s)
RESULTS    : PASS 7 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 438.19 s
```

**Comment by gbraad** [comment]
retest this please

**Comment by gbraad** [comment]
@budhrg build failed due to a missing dependency in the Avocado package: https://github.com/avocado-framework/avocado/issues/1798. Have added a temporary workaround by including `python-setuptools` to our CI script. 

Build succeeded now.

**Comment by LalatenduMohanty** [comment]
@gbraad Looks good to me . I will test the PR and merge it. Thanks

**Comment by gbraad** [comment]
you can do something like `minishift ssh "mount -t cifs -o
username=[user],password=[pw] //[uncpath] /mnt/[mountpoint]"` to test.

**Comment by brgnepal** [comment]
> Have added a temporary workaround by including python-setuptools to our CI script.

:+1:  I have tested locally and it was working fine. Now since we know CI is failing due to missing dependency and after adding it CI passed, I am fine to merge this PR

LGTM .

I will wait for @LalatenduMohanty review.

**Review by LalatenduMohanty — APPROVED** [review]

**Pull request merged**
