### PR TITLE
Issue #77 Fixing the tests to run on macOS

### PR DESCRIPTION
**Pull request by LalatenduMohanty**

### CODE REVIEW

**Review by brgnepal — CHANGES_REQUESTED** [review]
Please review Windows from here.

Supporting in Windows need a complete documentation. Not able to run and don't want to invest time either.

```
PS C:\> cd .\redhat\minishift-b2d-iso\
PS C:\redhat\minishift-b2d-iso> python -V
Python 2.7.14
PS C:\redhat\minishift-b2d-iso>
PS C:\redhat\minishift-b2d-iso>
PS C:\redhat\minishift-b2d-iso>
PS C:\redhat\minishift-b2d-iso> make test
Traceback (most recent call last):
  File "tests/utils/minishift_latest_version.py", line 3, in <module>
    import requests
ImportError: No module named requests
Traceback (most recent call last):
  File "tests/utils/minishift_latest_version.py", line 3, in <module>
    import requests
ImportError: No module named requests
Traceback (most recent call last):
  File "tests/utils/minishift_latest_version.py", line 3, in <module>
    import requests
ImportError: No module named requests
Downloading latest minishift binary at /cygdrive/c/redhat/minishift-b2d-iso/build/bin/minishift...
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
make: *** [/cygdrive/c/redhat/minishift-b2d-iso/build/bin/minishift] Error 2
PS C:\redhat\minishift-b2d-iso> pip install request
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ pip install request
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\redhat\minishift-b2d-iso> python.exe -m pip install requests
Collecting requests
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |################################| 92kB 71kB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 261kB/s
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    100% |################################| 337kB 384kB/s
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |################################| 133kB 344kB/s
Collecting idna<2.7,>=2.5 (from requests)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |################################| 61kB 491kB/s
Installing collected packages: chardet, certifi, urllib3, idna, requests
Successfully installed certifi-2017.11.5 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
PS C:\redhat\minishift-b2d-iso> make test
Downloading latest minishift binary at /cygdrive/c/redhat/minishift-b2d-iso/build/bin/minishift...
######################################################################## 100.0%
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
make: *** [/cygdrive/c/redhat/minishift-b2d-iso/build/bin/minishift] Error 2
```

**Comment by LalatenduMohanty** [comment]
@budhrg Updated the commit message to only add macOS. The script itself would work fine for Windows also but running the complete test on Windows is a different challenge I guess.

**Comment by brgnepal** [comment]
>  The script itself would work fine for Windows also but running the complete test on Windows is a different challenge I guess.

Yes,

**Comment by brgnepal** [comment]
Working fine for me. :+1:

**Pull request merged**
