### PR TITLE
cut v1.1.0

### PR DESCRIPTION
**Pull request by praveenkumar**
@budhrg Have a look.

### CODE REVIEW

**Comment by brgnepal** [comment]
@praveenkumar , why not only `cut v1.1.0` as commit message?

**Comment by praveenkumar** [comment]
@budhrg Done 👍

**Comment by brgnepal** [comment]
LGTM :+1:

**Comment by gbraad** [comment]
I wondered the same. breaks consistency...

**Comment by hferentschik** [comment]
Let's not forget to update the default B2D ISO version in Minishift after the release. I guess we can use https://github.com/minishift/minishift/issues/484 for at.

**Pull request merged**
