### PR TITLE
Issue #27 Exporting artifacts to a storage box

### LINKED ISSUE #27: Exporting artifacts to a storage box
See https://github.com/minishift/minishift-ci-jobs/issues/1#issuecomment-280229034

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #27 

@hferentschik , it addresses the push of artifacts on successful build of PR and master.

Job are already present to address this - https://ci.centos.org/job/minishift-b2d-iso/

### CODE REVIEW

**Comment by brgnepal** [comment]
retest this please

**Comment by brgnepal** [comment]
retest this please

**Comment by hferentschik** [comment]
> https://ci.centos.org/job/minishift-b2d-iso-build-master/

Is this the right job name? Is it not https://ci.centos.org/job/minishift-b2d-iso/ and https://ci.centos.org/job/minishift-b2d-iso-pr?

It makes sense imo to align the naming across all our repos and CentOS CI builds.

**Comment by brgnepal** [comment]
Yes @hferentschik , forgot to update the description.

If you see the README changes, it reflect the same.

**Review by hferentschik — APPROVED** [review]

**Comment by hferentschik** [comment]
Merged, thanks

**Pull request merged**
