### PR TITLE
Issue #69 added --force flag to minishift vm delete test

### LINKED ISSUE #69: Update test to force delete minishift instance
With latest 1.6.0, we have added confirmation on delete operation. Update test accordingly.

### PR DESCRIPTION
**Pull request by anjannath**
Fix #69

### CODE REVIEW

**Comment by brgnepal** [comment]
add to whitelist

**Review by brgnepal — APPROVED** [review]
LGTM :+1:

**Comment by brgnepal** [comment]
Merged and thanks

**Comment by anjannath** [comment]
No Problem!

**Pull request closed without merging**
